### ISSUE TITLE
QA - navbar unresponsive on smaller devices

### ISSUE THREAD

**Issue by Miraii133** [icecubes99/emmanuelaguado#1]
Very clean resume I hope you don't mind the random QA 

Issue:
![image](https://github.com/user-attachments/assets/d6e9b4d1-b2b9-48eb-8059-ba6f68b0aea6)

Should be:
Socials and contact me button should not be close to each other

**Comment by icecubes99** [comment]
added gaps to the navbar, thanks for the QA again!!! hehe
