### ISSUE TITLE
QA - socials card suggest implementing redirect when clicking each social card

### ISSUE THREAD

**Issue by Miraii133** [icecubes99/emmanuelaguado#2]
Issue:
![image](https://github.com/user-attachments/assets/8bd032c6-009a-4408-93ce-564de57281ee)

Should be:
More like a suggestion:
1. Would be great if clicking the social card component acts if you clicked the "Connect" button, ORRR
2. I suggest you make the "Connect" call to action clearer by adding a fill to the button or maybe an outline to make it clearer

**Comment by icecubes99** [comment]
added a fill to the connect button
